spring.application.name=task-management-api
spring.datasource.url=jdbc:postgresql://localhost:5432/TaskMgmt?currentSchema=taskmanagementapi
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080